/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matteo.vc.jni;

public final class VcCallState {
  public final static VcCallState UNKNOW = new VcCallState("UNKNOW", VCJNI.UNKNOW_get());
  public final static VcCallState ESTABLISHING = new VcCallState("ESTABLISHING", VCJNI.ESTABLISHING_get());
  public final static VcCallState ESTABLISHED = new VcCallState("ESTABLISHED", VCJNI.ESTABLISHED_get());
  public final static VcCallState CONFIRMED = new VcCallState("CONFIRMED", VCJNI.CONFIRMED_get());
  public final static VcCallState DISCONNECT = new VcCallState("DISCONNECT", VCJNI.DISCONNECT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VcCallState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VcCallState.class + " with value " + swigValue);
  }

  private VcCallState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VcCallState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VcCallState(String swigName, VcCallState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VcCallState[] swigValues = { UNKNOW, ESTABLISHING, ESTABLISHED, CONFIRMED, DISCONNECT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

