/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matteo.vc.jni;

public class VcCall {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VcCall(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VcCall obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VCJNI.delete_VcCall(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VcCall(VcFriend arg0, VcCallState state, boolean isOutgo) {
    this(VCJNI.new_VcCall__SWIG_0(VcFriend.getCPtr(arg0), arg0, state.swigValue(), isOutgo), true);
  }

  public VcCall(VcFriend arg0, VcCallState state) {
    this(VCJNI.new_VcCall__SWIG_1(VcFriend.getCPtr(arg0), arg0, state.swigValue()), true);
  }

  public VcCall(VcFriend arg0) {
    this(VCJNI.new_VcCall__SWIG_2(VcFriend.getCPtr(arg0), arg0), true);
  }

  public int getId() {
    return VCJNI.VcCall_getId(swigCPtr, this);
  }

  public VcFriend getFriend() {
    long cPtr = VCJNI.VcCall_getFriend(swigCPtr, this);
    return (cPtr == 0) ? null : new VcFriend(cPtr, false);
  }

  public VcCallState getState() {
    return VcCallState.swigToEnum(VCJNI.VcCall_getState(swigCPtr, this));
  }

  public boolean isOutgo() {
    return VCJNI.VcCall_isOutgo(swigCPtr, this);
  }

}
