/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matteo.vc.jni;

public final class VcCallAction {
  public final static VcCallAction CALL_ACTION_ANSWER = new VcCallAction("CALL_ACTION_ANSWER", VCJNI.CALL_ACTION_ANSWER_get());
  public final static VcCallAction CALL_ACTION_REJECT = new VcCallAction("CALL_ACTION_REJECT");
  public final static VcCallAction CALL_ACTION_HANGUP = new VcCallAction("CALL_ACTION_HANGUP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VcCallAction swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VcCallAction.class + " with value " + swigValue);
  }

  private VcCallAction(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VcCallAction(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VcCallAction(String swigName, VcCallAction swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VcCallAction[] swigValues = { CALL_ACTION_ANSWER, CALL_ACTION_REJECT, CALL_ACTION_HANGUP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

