/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matteo.vc.jni;

public class VcFriend {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VcFriend(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VcFriend obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VCJNI.delete_VcFriend(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VcFriend(long ssrc, String ip, int port) {
    this(VCJNI.new_VcFriend(ssrc, ip, port), true);
  }

  public int getSsrc() {
    return VCJNI.VcFriend_getSsrc(swigCPtr, this);
  }

  public String getIp() {
    return VCJNI.VcFriend_getIp(swigCPtr, this);
  }

  public int getPort() {
    return VCJNI.VcFriend_getPort(swigCPtr, this);
  }

}
