/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matteo.vc.jni;

public class VcManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VcManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VcManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public int makeCall(long friendSsrc) {
    return VCJNI.VcManager_makeCall(swigCPtr, this, friendSsrc);
  }

  public void addFriend(long ssrc, String ip, int port) {
    VCJNI.VcManager_addFriend(swigCPtr, this, ssrc, ip, port);
  }

  public void clearFriend() {
    VCJNI.VcManager_clearFriend(swigCPtr, this);
  }

  public VcCall getCurrentCall() {
    long cPtr = VCJNI.VcManager_getCurrentCall(swigCPtr, this);
    return (cPtr == 0) ? null : new VcCall(cPtr, false);
  }

  public void setCallback(VcCallback arg0) {
    VCJNI.VcManager_setCallback(swigCPtr, this, VcCallback.getCPtr(arg0), arg0);
  }

  public void handleCall(VcCall call, VcCallAction action) {
    VCJNI.VcManager_handleCall(swigCPtr, this, VcCall.getCPtr(call), call, action.swigValue());
  }

  public int pushYv12Frame(String buffer, long length) {
    return VCJNI.VcManager_pushYv12Frame(swigCPtr, this, buffer, length);
  }

  public void setMyCameraParameters(int height, int width, int fps) {
    VCJNI.VcManager_setMyCameraParameters(swigCPtr, this, height, width, fps);
  }

  public void initGl(int viewWidth, int viewHeight, String buildModel) {
    VCJNI.VcManager_initGl(swigCPtr, this, viewWidth, viewHeight, buildModel);
  }

  public void deinitGl() {
    VCJNI.VcManager_deinitGl(swigCPtr, this);
  }

  public void render() {
    VCJNI.VcManager_render(swigCPtr, this);
  }

  public static VcManager init(String localIp, int port, long ssrc) {
    long cPtr = VCJNI.VcManager_init__SWIG_0(localIp, port, ssrc);
    return (cPtr == 0) ? null : new VcManager(cPtr, false);
  }

  public static VcManager init(String localIp, int port) {
    long cPtr = VCJNI.VcManager_init__SWIG_1(localIp, port);
    return (cPtr == 0) ? null : new VcManager(cPtr, false);
  }

  public static void deinit() {
    VCJNI.VcManager_deinit();
  }

  public static VcManager get() {
    long cPtr = VCJNI.VcManager_get();
    return (cPtr == 0) ? null : new VcManager(cPtr, false);
  }

}
